pipeline {
  agent  { docker { image 'python:3.12.0-alpine3.18' } }

  stages {
    stage('Install') {
      steps {
        sh 'sudo pip install --upgrade pip'
        sh 'sudo pip install -r requirements.txt'
      }
    }
    stage('Lint') {
      steps {
        sh 'flake8 app tests'
      }
    }
    stage('Test') {
      steps {
        sh 'pytest --cov=app --cov-report=term-missing'
      }
    }
  }
  post {
    success { echo "CI Passed" }
    failure { echo "CI Failed" }
  }
}
